/**
 * Loads data-source/lesson_phrases.csv (generated by generatePhraseCsv.js + generate_phrase_audio.py)
 * into the phrases/lesson_phrases tables.
 *
 * - phrases.difficulty only supports the legacy BEGINNER/INTERMEDIATE/ADVANCED enum (no CEFR
 *   column like words has), so the CSV's A1-C1 level is mapped down: A1/A2 -> BEGINNER,
 *   B1/B2 -> INTERMEDIATE, C1/C2 -> ADVANCED (same tiers the words table used before its CEFR split).
 * - phrase_en has a UNIQUE constraint, so re-running this script is safe: existing phrases get
 *   updated in place (ON CONFLICT DO UPDATE) rather than duplicated, and lesson_phrases links are
 *   ON CONFLICT DO NOTHING.
 *
 * Usage: node importLessonPhrases.js
 */
const { Pool } = require('pg');
const path = require('path');
const fs = require('fs');
require('dotenv').config({ path: path.resolve(__dirname, '../.env') });

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
  ssl: { rejectUnauthorized: false },
});

const CSV_PATH = path.resolve(__dirname, '../../../data-source/lesson_phrases.csv');

const CEFR_TO_DIFFICULTY = {
  A1: 'BEGINNER', A2: 'BEGINNER',
  B1: 'INTERMEDIATE', B2: 'INTERMEDIATE',
  C1: 'ADVANCED', C2: 'ADVANCED',
};

// Minimal RFC4180-style CSV parser (handles quoted fields with embedded commas/newlines/escaped quotes) —
// this CSV has long quoted sentences, so naive split(',') would break.
function parseCsv(text) {
  const rows = [];
  let row = [];
  let field = '';
  let inQuotes = false;

  for (let i = 0; i < text.length; i++) {
    const char = text[i];
    if (inQuotes) {
      if (char === '"') {
        if (text[i + 1] === '"') { field += '"'; i++; }
        else { inQuotes = false; }
      } else {
        field += char;
      }
    } else if (char === '"') {
      inQuotes = true;
    } else if (char === ',') {
      row.push(field);
      field = '';
    } else if (char === '\n') {
      row.push(field);
      rows.push(row);
      row = [];
      field = '';
    } else if (char === '\r') {
      // skip, \n handles the row break
    } else {
      field += char;
    }
  }
  if (field.length > 0 || row.length > 0) {
    row.push(field);
    rows.push(row);
  }
  return rows;
}

async function main() {
  const text = fs.readFileSync(CSV_PATH, 'utf-8');
  const [header, ...rows] = parseCsv(text).filter(r => r.length > 1 || r[0] !== '');
  const col = (row, name) => row[header.indexOf(name)];

  console.log(`Loaded ${rows.length} phrase rows from CSV.`);

  let inserted = 0, linked = 0, skipped = 0;

  for (const row of rows) {
    const lessonId = parseInt(col(row, 'lesson_id'));
    const cefrLevel = col(row, 'cefr_level');
    const phraseEn = col(row, 'phrase_en');
    const phraseBn = col(row, 'phrase_bn');
    const audioUrl = col(row, 'audio_url') || null;
    const difficulty = CEFR_TO_DIFFICULTY[cefrLevel] || 'BEGINNER';

    if (!lessonId || !phraseEn || !phraseBn) {
      console.warn('  Skipping malformed row:', row);
      skipped++;
      continue;
    }

    try {
      const { rows: [phrase] } = await pool.query(
        `INSERT INTO phrases (phrase_en, phrase_bn, audio_url, difficulty)
         VALUES ($1, $2, $3, $4)
         ON CONFLICT (phrase_en) DO UPDATE SET phrase_bn = $2, audio_url = $3, difficulty = $4
         RETURNING id`,
        [phraseEn, phraseBn, audioUrl, difficulty]
      );
      inserted++;

      const { rowCount } = await pool.query(
        `INSERT INTO lesson_phrases (lesson_id, phrase_id) VALUES ($1, $2) ON CONFLICT DO NOTHING`,
        [lessonId, phrase.id]
      );
      if (rowCount > 0) linked++;
    } catch (err) {
      console.error(`  Failed for "${phraseEn}":`, err.message);
      skipped++;
    }
  }

  console.log(`\nDone. ${inserted} phrases upserted, ${linked} new lesson links created, ${skipped} skipped.`);
  await pool.end();
}

main().catch(err => {
  console.error('Fatal error:', err);
  process.exit(1);
});
